### ISSUE TITLE
Docker link in the README is a dead end

### ISSUE THREAD

**Issue by hotmeatballsoup** [bubenkoff/vagrant-docker-example#5]
Hi there - the link for the Docker install on your README goes to a 404-style page that says: "*Ain't nothing here, best you mosey along.*"

Can you either update the README with the correct/supported Docker installation link, or point me in the right direction?

I know I could just Google "*install Docker*" but the reason why I found your project here is that I previously had Vagrant and Docker installed on my Mac, but the Docker installation seemed to hose my Vagrant/VirtualBox connection ([here's the related StackOverflow question](http://stackoverflow.com/questions/32085381/vagrant-and-docker-not-playing-nice)). I ended up just uninstalling both Vagrant and Docker, and so now I'm trying again.

If you've figured out how to get Vagrant and Docker working together, I'll just piggyback off of your hard work (!), which is why I'm asking for the specific Docker installation link that your `Vagrantfile` will work with.

Thanks!

**Comment by bubenkoff** [comment]
You may notice the docs look different
You also may find a few broken links or other wonkiness. We are working on fixing these things. We appreciate your patience while we go through our growing pains.

that's from docker docs site

If you're on mac, use http://docs.docker.com/mac/started/

**Comment by hotmeatballsoup** [comment]
Thanks for getting back to me @bubenkoff!

Are you *absolutely positive* that the latest Vagrant and Docker installations are compatible with each other on Mac OS (I'm on 10.10.4)? I ask because the link you posted above is the same link I installed Docker from a few nights back.

If you read that StackOverflow question, you'll see that I hd Vagrant working just fine, then installed Docker (same link as you posted above), and then Vagrant stopped working. If you peruse the Vagrant source code, you'll see that the error message I'm seeing comes from [this line of code here](https://github.com/mitchellh/vagrant/blob/cb51b4fe7f92232ff9cf12f93e1207be619b1405/lib/vagrant/environment.rb#L382).

I imagine that, for VBox, that `usable` method is defined [here](https://github.com/mitchellh/vagrant/blob/cb51b4fe7f92232ff9cf12f93e1207be619b1405/plugins/providers/virtualbox/provider.rb#L8), but that's about as far upstream as I've been able to track it.

At the end of the day, all I'm looking to do is have both installed and working, so I can clone your `Vagrantfile` and run a Docker container through Vagrant. If you think that installation link is now working, I'll give it a try! Otherwise I'll have to keep trying to look at the Vagrant source code to surmise what is happening.

Thanks again for any and all help here!

**Comment by bubenkoff** [comment]
i'll check on my mac and get back to use
i don't use mac for development, because it does not support containers natively, and using the proxy vm is not an option for projects develop

**Comment by hotmeatballsoup** [comment]
Thanks for helping me with this! There definitely seems to be something wonky with Vagrant/Docker/VirtualBox on Macs, I am seeing similar issues from other Google searches, but no one has posted the solution/fix.

**Comment by bubenkoff** [comment]
i've pushed changes to the readme
please follow the steps for mac and let me know
for me it worked fine (checked on mac with latest everything: OS, virtualbox, docker toolbox, brew)

**Comment by ghost** [comment]
Thank you sir! What ever you did, this is working for me now - thanks again for being so responsive!

**Comment by bubenkoff** [comment]
glad it worked, it's a pleasure to help!
